"""Add category column to learning_module

Revision ID: 914fa5375f20
Revises: e67cfa320dbd
Create Date: 2026-01-22 07:41:16.399472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '914fa5375f20'
down_revision = 'e67cfa320dbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('learning_module', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('learning_module', schema=None) as batch_op:
        batch_op.drop_column('category')

    # ### end Alembic commands ###
