"""Add created_at and last_login columns

Revision ID: dc1bcab62811
Revises: 
Create Date: 2026-01-21 18:55:08.985617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc1bcab62811'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vigenere_challenge_attempt')
    op.drop_table('premium_transaction')
    op.drop_table('vigenere_usage')
    op.drop_table('vigenere_quiz_attempt')
    op.drop_table('vigenere_quiz_question')
    op.drop_table('premium_subscription')
    op.drop_table('vigenere_challenge')
    op.drop_table('premium_code')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_login', sa.DateTime(), nullable=True))
        batch_op.alter_column('bio',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.drop_column('phone')
        batch_op.drop_column('join_date')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('last_name', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('join_date', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.VARCHAR(length=20), nullable=True))
        batch_op.alter_column('bio',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.drop_column('last_login')
        batch_op.drop_column('created_at')

    op.create_table('premium_code',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('code', sa.VARCHAR(length=50), nullable=False),
    sa.Column('code_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('duration_days', sa.INTEGER(), nullable=True),
    sa.Column('max_uses', sa.INTEGER(), nullable=True),
    sa.Column('used_count', sa.INTEGER(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=50), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('expires_at', sa.DATETIME(), nullable=True),
    sa.Column('description', sa.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('vigenere_challenge',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.VARCHAR(length=500), nullable=True),
    sa.Column('plaintext', sa.VARCHAR(length=500), nullable=True),
    sa.Column('ciphertext', sa.VARCHAR(length=500), nullable=True),
    sa.Column('key', sa.VARCHAR(length=100), nullable=True),
    sa.Column('solution', sa.VARCHAR(length=500), nullable=False),
    sa.Column('hint', sa.VARCHAR(length=200), nullable=True),
    sa.Column('difficulty', sa.VARCHAR(length=20), nullable=True),
    sa.Column('xp_reward', sa.INTEGER(), nullable=True),
    sa.Column('category', sa.VARCHAR(length=50), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('premium_subscription',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('subscription_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('start_date', sa.DATETIME(), nullable=True),
    sa.Column('end_date', sa.DATETIME(), nullable=True),
    sa.Column('payment_method', sa.VARCHAR(length=50), nullable=True),
    sa.Column('transaction_id', sa.VARCHAR(length=100), nullable=True),
    sa.Column('premium_code', sa.VARCHAR(length=50), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('vigenere_quiz_question',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('question', sa.VARCHAR(length=500), nullable=False),
    sa.Column('option_a', sa.VARCHAR(length=200), nullable=True),
    sa.Column('option_b', sa.VARCHAR(length=200), nullable=True),
    sa.Column('option_c', sa.VARCHAR(length=200), nullable=True),
    sa.Column('option_d', sa.VARCHAR(length=200), nullable=True),
    sa.Column('correct_answer', sa.VARCHAR(length=1), nullable=False),
    sa.Column('explanation', sa.VARCHAR(length=1000), nullable=True),
    sa.Column('difficulty', sa.VARCHAR(length=20), nullable=True),
    sa.Column('xp_reward', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vigenere_quiz_attempt',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('score', sa.INTEGER(), nullable=True),
    sa.Column('total_questions', sa.INTEGER(), nullable=True),
    sa.Column('xp_earned', sa.INTEGER(), nullable=True),
    sa.Column('completed_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vigenere_usage',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('encryptions_count', sa.INTEGER(), nullable=True),
    sa.Column('decryptions_count', sa.INTEGER(), nullable=True),
    sa.Column('last_used', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('premium_transaction',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('transaction_id', sa.VARCHAR(length=100), nullable=False),
    sa.Column('amount', sa.FLOAT(), nullable=False),
    sa.Column('currency', sa.VARCHAR(length=10), nullable=True),
    sa.Column('plan_type', sa.VARCHAR(length=20), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('payment_method', sa.VARCHAR(length=50), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('completed_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_id')
    )
    op.create_table('vigenere_challenge_attempt',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('challenge_id', sa.INTEGER(), nullable=False),
    sa.Column('answer', sa.VARCHAR(length=500), nullable=True),
    sa.Column('is_correct', sa.BOOLEAN(), nullable=True),
    sa.Column('xp_earned', sa.INTEGER(), nullable=True),
    sa.Column('attempts', sa.INTEGER(), nullable=True),
    sa.Column('completed_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['challenge_id'], ['vigenere_challenge.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
