"""Add difficulty column to video_course

Revision ID: e67cfa320dbd
Revises: dc1bcab62811
Create Date: 2026-01-22 07:32:49.631823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e67cfa320dbd'
down_revision = 'dc1bcab62811'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('forum_post')
    op.drop_table('tutorial_reference')
    op.drop_table('user_tutorial_bookmark')
    op.drop_table('tutorial')
    op.drop_table('forum_topic')
    op.drop_table('user_tutorial_progress')
    op.drop_table('tutorial_category')
    with op.batch_alter_table('video_course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('difficulty', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('order', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('views', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('likes', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('url',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video_course', schema=None) as batch_op:
        batch_op.alter_column('url',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('likes')
        batch_op.drop_column('views')
        batch_op.drop_column('order')
        batch_op.drop_column('difficulty')

    op.create_table('tutorial_category',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('slug', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('icon', sa.VARCHAR(length=50), nullable=True),
    sa.Column('color', sa.VARCHAR(length=20), nullable=True),
    sa.Column('tutorial_count', sa.INTEGER(), nullable=True),
    sa.Column('order', sa.INTEGER(), nullable=True),
    sa.Column('is_premium', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('user_tutorial_progress',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('tutorial_id', sa.INTEGER(), nullable=False),
    sa.Column('completed', sa.BOOLEAN(), nullable=True),
    sa.Column('progress_percentage', sa.INTEGER(), nullable=True),
    sa.Column('time_spent_minutes', sa.INTEGER(), nullable=True),
    sa.Column('started_at', sa.DATETIME(), nullable=True),
    sa.Column('completed_at', sa.DATETIME(), nullable=True),
    sa.Column('last_accessed', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['tutorial_id'], ['tutorial.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'tutorial_id', name=op.f('_user_tutorial_uc'))
    )
    op.create_table('forum_topic',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('category', sa.VARCHAR(length=50), nullable=True),
    sa.Column('created_by', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('last_activity', sa.DATETIME(), nullable=True),
    sa.Column('is_pinned', sa.BOOLEAN(), nullable=True),
    sa.Column('is_locked', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tutorial',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), nullable=False),
    sa.Column('slug', sa.VARCHAR(length=200), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('content', sa.TEXT(), nullable=True),
    sa.Column('difficulty', sa.VARCHAR(length=20), nullable=True),
    sa.Column('duration_minutes', sa.INTEGER(), nullable=True),
    sa.Column('category', sa.VARCHAR(length=50), nullable=True),
    sa.Column('tags', sa.VARCHAR(length=500), nullable=True),
    sa.Column('is_premium', sa.BOOLEAN(), nullable=True),
    sa.Column('is_new', sa.BOOLEAN(), nullable=True),
    sa.Column('featured', sa.BOOLEAN(), nullable=True),
    sa.Column('estimated_reading_time', sa.INTEGER(), nullable=True),
    sa.Column('references', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('order', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('user_tutorial_bookmark',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('tutorial_id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['tutorial_id'], ['tutorial.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'tutorial_id', name=op.f('_user_tutorial_bookmark_uc'))
    )
    op.create_table('tutorial_reference',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('tutorial_id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), nullable=False),
    sa.Column('url', sa.VARCHAR(length=500), nullable=False),
    sa.Column('source', sa.VARCHAR(length=100), nullable=True),
    sa.Column('icon', sa.VARCHAR(length=50), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['tutorial_id'], ['tutorial.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('forum_post',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('topic_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['forum_topic.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
